name: Add Latest Widget

on:
workflow_dispatch:

jobs:
update:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'
  - name: Run Script
    run: python add_latest.py
  - name: Commit Changes
    run: |
      git config user.name "github-actions"
      git config user.email "actions@github.com"
      git add .
      if ! git diff --cached --quiet; then
        git commit -m "Add latest widget"
        git push
      fi
